name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Allows you to run this manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fix Permissions
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rummy-apk
          path: app/build/outputs/apk/debug/*.apk
